security:
  authenticator:
    cls_or_fn: _ravnar.authenticators.BearerTokenAuthenticator
    params:
      token_validator:
        cls_or_fn: _ravnar.authenticators.OIDCTokenValidator
        params:
          issuer: '{{ required "oidc.issuer is required" .Values.oidc.issuer }}'
          default_permissions:
            - threads:read
            - threads:write
            - threads:delete
            - agents:read
