{{- define "nebariApp" -}}
{{- $top := .top -}}
{{- $component := .component -}}
{{- include "nebari-app.nebariApp" (dict
    "metadata" (dict
      "name"      (include "ravnar.component-name" (dict "top" $top "component" $component))
      "namespace" $top.Release.Namespace
      "labels"    (include "ravnar.labels" (dict "top" $top "component" $component) | fromYaml)
    )
    "spec" .spec
) -}}
{{- end -}}
{{- $component := "nebariapp" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    nebari.dev/managed: "true"
    {{- include "ravnar.labels" (dict "top" . "component" $component) | nindent 4 }}
---
{{- $component := "backend" }}
{{- with include "nebari-chat.ravnarContextJson" . | fromJson }}
{{- include "nebariApp" (dict
    "top" $
    "component" $component
    "spec" (mergeOverwrite (dict
      "service" (dict
        "name" (include "ravnar.fullname" .)
        "port" .Values.service.port
      )
    ) $.Values.backend.nebariApp)
) }}
{{- end }}
---
{{- $component := "frontend" }}
{{- include "nebariApp" (dict
    "top" $
    "component" $component
    "spec" (mergeOverwrite (dict
      "service" (dict
        "name" (include "ravnar.component-name" (dict "top" . "component" $component))
        "port" .Values.frontend.service.port
      )
    ) .Values.frontend.nebariApp)
) }}
