{{- if .Values.frontend.enabled }}
{{- $component := "frontend" }}
{{- include "nebari-chat.nebariapp" (dict
    "top" .
    "component" $component
    "service" (dict
      "name" (include "ravnar.component-name" (dict "top" . "component" $component))
      "port" .Values.frontend.service.port
    )
    "nebariapp" .Values.frontend.nebariapp
) }}
{{- end }}
